### ISSUE TITLE
Missing sessionStore -- cannot call method 'set' of undefined

### ISSUE THREAD

**Issue by brekk** [techpines/express.io#4] opened 2013-01-15 04:47 UTC
Hey there,

I was recently trying to get the Sessions example to work, and I kept getting this error:

```
TypeError: Cannot call method 'set' of undefined
at Session.save ([...]/node_modules/express.io/node_modules/connect/lib/middleware/session/session.js:63:25)
```

But I was able to fix it by modifying the io authorization handshake and adding this line:

```
data.sessionStore = sessionConfig.store
```

Before the `sessionConfig.store.get` code on line 55.

Cheers,

Brekk

**Comment by techpines** [comment] 2013-01-15 15:53
@brekk Thanks for the heads up.  I made the code change and pushed it out.  

There is actually one more issue here.  Using sessions and Redis as a pub/sub server won't allow you to use the normal session object.  The problem is that the sessionStore might have circular references in it, and that whole `data` object gets persisted, and blows up because of circular JSON issues.  

I should have this second issue fixed in the next day or so.

**Comment by techpines** [comment] 2013-01-16 02:32
I believe all session issues are resolved for express.io@1.1.8

Let me know if you run into anymore problems.

**Closed as completed** 2013-01-16 14:20 UTC

**Comment by brekk** [comment] 2013-01-16 16:34
Thanks Brad!

No issues on my end.
